apiVersion: apps/v1
kind: Deployment
metadata:
  name: att
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: ACCOUNT_NUMBER_TOKEN.dkr.ecr.AWS_REGION_TOKEN.amazonaws.com/att:latest
          ports:
            - containerPort: 8080
