apiVersion: apps/v1
kind: Deployment
metadata:
  name: att
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 207188242297.dkr.ecr.eu-west-2.amazonaws.com/att:latest
          ports:
            - containerPort: 8080
